# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' simulateFixedTreeCodeNew
#'
#' Runs simulation of a tree containing Fixed Population Size objects
#' [FixedPops & DiffTriangles].
#'
#'@param nObs number of observations for simulation time
#'@param traverseFrequency how often to output entire system population to filesystem
#'@param indir input directory for tree files
#'@param outdir output directory
#'@param seed numeric seed for random number generator
#'
#' @export
simulateFixedTreeCodeNew <- function(nObs = 10L, traverseFrequency = -1L, indir = "./", outdir = "./", seed = NULL) {
    .Call('_diffpop_simulateFixedTreeCodeNew', PACKAGE = 'diffpop', nObs, traverseFrequency, indir, outdir, seed)
}

#' simulateTreeCodeNew
#'
#' Runs simulation of a tree structure using Gillespie algorithm
#'
#'@param nObs number of observations for simulation time
#'@param traverseFrequency how often to output entire system population to filesystem
#'@param indir input directory for tree files
#'@param outdir output directory
#'@param seed numeric seed for random number generator
#'
#' @export
simulateTreeCodeNew <- function(nObs = 10L, traverseFrequency = -1L, indir = "./", outdir = "./", seed = NULL) {
    .Call('_diffpop_simulateTreeCodeNew', PACKAGE = 'diffpop', nObs, traverseFrequency, indir, outdir, seed)
}

